version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - host
  spottybot:
    container_name: spottybot
    image: spottybot-1.0
    restart: always
    depends_on:
      - mongo
    links:
      - mongo:mongodb
    networks:
      - host
    ports:
      - "8080:8080"